from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class EmulatorAdapter(Protocol):
    """Minimal emulator contract required by the hunting engine."""

    def get_game_title(self) -> str: ...
    def get_rom_checksum(self) -> str: ...
    def read_u8(self, address: int) -> int: ...
    def read_u16(self, address: int) -> int: ...
    def read_u32(self, address: int) -> int: ...
    def set_keys(self, mask: int) -> None: ...
    def run_frame(self) -> None: ...
    def reset(self) -> None: ...
    def save_state(self, path: Path) -> None: ...
    def load_state(self, path: Path) -> None: ...
    def screenshot(self, path: Path) -> None: ...


class AdapterInvariantError(RuntimeError):
    """Raised when emulator behavior violates a safety invariant."""
